//
// V1ExportLogsPartialSuccess.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
	import AnyCodable
#endif

@available(*, deprecated, renamed: "OTLP.V1ExportLogsPartialSuccess")
typealias V1ExportLogsPartialSuccess = OTLP.V1ExportLogsPartialSuccess

extension OTLP {
	struct V1ExportLogsPartialSuccess: Codable, Hashable {
		/** The number of rejected log records.  A `rejected_<signal>` field holding a `0` value indicates that the request was fully accepted. */
		var rejectedLogRecords: String?
		/** A developer-facing human-readable message in English. It should be used either to explain why the server rejected parts of the data during a partial success or to convey warnings/suggestions during a full success. The message should offer guidance on how users can address such issues.  error_message is an optional field. An error_message with an empty value is equivalent to it not being set. */
		var errorMessage: String?

		init(rejectedLogRecords: String? = nil, errorMessage: String? = nil) {
			self.rejectedLogRecords = rejectedLogRecords
			self.errorMessage = errorMessage
		}

		enum CodingKeys: String, CodingKey, CaseIterable {
			case rejectedLogRecords
			case errorMessage
		}

		// Encodable protocol methods

		func encode(to encoder: Encoder) throws {
			var container = encoder.container(keyedBy: CodingKeys.self)
			try container.encodeIfPresent(rejectedLogRecords, forKey: .rejectedLogRecords)
			try container.encodeIfPresent(errorMessage, forKey: .errorMessage)
		}
	}
}
