//
// V1ExportMetricsServiceResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
	import AnyCodable
#endif

@available(*, deprecated, renamed: "OTLP.V1ExportMetricsServiceResponse")
typealias V1ExportMetricsServiceResponse = OTLP.V1ExportMetricsServiceResponse

extension OTLP {
	struct V1ExportMetricsServiceResponse: Codable, Hashable {
		var partialSuccess: V1ExportMetricsPartialSuccess?

		init(partialSuccess: V1ExportMetricsPartialSuccess? = nil) {
			self.partialSuccess = partialSuccess
		}

		enum CodingKeys: String, CodingKey, CaseIterable {
			case partialSuccess
		}

		// Encodable protocol methods

		func encode(to encoder: Encoder) throws {
			var container = encoder.container(keyedBy: CodingKeys.self)
			try container.encodeIfPresent(partialSuccess, forKey: .partialSuccess)
		}
	}
}
