//
// V1ExponentialHistogram.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
	import AnyCodable
#endif

@available(*, deprecated, renamed: "OTLP.V1ExponentialHistogram")
typealias V1ExponentialHistogram = OTLP.V1ExponentialHistogram

extension OTLP {
	/** ExponentialHistogram represents the type of a metric that is calculated by aggregating as a ExponentialHistogram of all reported double measurements over a time interval. */
	struct V1ExponentialHistogram: Codable, Hashable {
		var dataPoints: [V1ExponentialHistogramDataPoint]?
		var aggregationTemporality: V1AggregationTemporality?

		init(dataPoints: [V1ExponentialHistogramDataPoint]? = nil, aggregationTemporality: V1AggregationTemporality? = nil) {
			self.dataPoints = dataPoints
			self.aggregationTemporality = aggregationTemporality
		}

		enum CodingKeys: String, CodingKey, CaseIterable {
			case dataPoints
			case aggregationTemporality
		}

		// Encodable protocol methods

		func encode(to encoder: Encoder) throws {
			var container = encoder.container(keyedBy: CodingKeys.self)
			try container.encodeIfPresent(dataPoints, forKey: .dataPoints)
			try container.encodeIfPresent(aggregationTemporality, forKey: .aggregationTemporality)
		}
	}
}
