//
// V1ExportTraceServiceResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
	import AnyCodable
#endif

@available(*, deprecated, renamed: "OTLP.V1ExportTraceServiceResponse")
typealias V1ExportTraceServiceResponse = OTLP.V1ExportTraceServiceResponse

extension OTLP {
	struct V1ExportTraceServiceResponse: Codable, Hashable {
		var partialSuccess: V1ExportTracePartialSuccess?

		init(partialSuccess: V1ExportTracePartialSuccess? = nil) {
			self.partialSuccess = partialSuccess
		}

		enum CodingKeys: String, CodingKey, CaseIterable {
			case partialSuccess
		}

		// Encodable protocol methods

		func encode(to encoder: Encoder) throws {
			var container = encoder.container(keyedBy: CodingKeys.self)
			try container.encodeIfPresent(partialSuccess, forKey: .partialSuccess)
		}
	}
}
